version: 0.0
os: linux
files:
- source: /scripts
destination: /var/www
permissions:
- object: /var/www/
pattern: “**”
owner: ubuntu
group: ubuntu
mode: 775
hooks:
AfterInstall:
- location: scripts/dependencies_install.sh
runas: ubuntu
