version: 0.0
os: linux
files:
- source: /scripts
destination: /home/ubuntu/ruby
permissions:
- object: /home/ubuntu/ruby
pattern: “**”
owner: ubuntu
group: ubuntu
mode: 775
hooks:
AfterInstall:
- location: scripts/dependencies_install.sh
runas: ubuntu
